まだまだ途中ですが一度提出させていただきます
Yuina-Kage/05_learning_plan pull request #1
Opened 2020-02-15 16:42 UTC by Yuina-Kage

夜分遅くに失礼致します。
また、度々提出遅くなりまして申し訳ございません。

課題がまだまだ途中の段階なので引き続き進めていきますが一度提出させていただきます。
よろしくお願い致します！

![スクリーンショット 2020-02-16 1 36 34](https://user-images.githubusercontent.com/58411035/74591604-94177500-505c-11ea-9e79-c11a7e168a41.png)

2020-02-16 07:06 UTC, kazu-taka requested changes
@Yuina-Kage 
現在足りない処理(一部ですが)を記入したので、修正お願いします！

2020-02-16 07:06 UTC, kazu-taka commented on index.php
> +    $errors['title'] = '学習内容と期限を記入してください';
@Yuina-Kage 
期限はここではチェックしていないので、別でチェックをお願いします！

2020-02-16 07:06 UTC, kazu-taka commented on index.php
> +    $sql = "insert into plans (title, due_date, created_at, updated_at) values (:title, now(), now())";
@Yuina-Kage 
ここにも期限が入っていないので追加お願いします！

2020-02-16 07:06 UTC, kazu-taka commented on index.php
> +    $stmt->bindParam(":title", $title);
@Yuina-Kage 
ここでも期限の処理が必用なので、追加お願いします！

2020-02-16 07:06 UTC, kazu-taka commented on index.php
> +    <form action="" method="post">
@Yuina-Kage 
学習内容はフォームで送信する値なので、formタグの中に入れて下さい✨

2020-02-28 23:05 UTC, Yuina-Kage commented
お疲れさまです。
提出遅くなり申し訳ございません。
課題つまづいてしまいました。

<期待する動作>
学習内容と期限日を入力し追加ボタンを押すと追加することができる

<うまくいかない点 or エラーの内容>
期限日を入力して追加ボタンを押すと "期限を入力してください"というエラー表示がでる
編集ページでも同じことが起きている

<自分なりに考えて試した点>
新規追加に必要なものをindex.htmlの19行目から46行目に記入
'title'と'due_date'、2つ分書いています

よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/58411035/75593751-b92ecd80-5ac9-11ea-829a-d8cb498ec089.png)
![image](https://user-images.githubusercontent.com/58411035/75593760-c1870880-5ac9-11ea-92d6-a444eed84534.png)
![image](https://user-images.githubusercontent.com/58411035/75593777-cba90700-5ac9-11ea-8e32-e2357e677146.png)
![image](https://user-images.githubusercontent.com/58411035/75593787-d2d01500-5ac9-11ea-99c5-a5c2db645d53.png)

2020-02-29 02:24 UTC, Arisaarisa reviewed
入力が繁栄されない時はデータベースと紐付いてないsql文と紐付いてないというのを疑ってみて下さい！
今回はhtmlの中でnameがsqlと紐付いてなかったので反映されなかった感じです！

2020-02-29 02:24 UTC, Arisaarisa commented on edit.php
> +    <input type="date" name="date" value="<?php echo h($plan['due_date']); ?>">
ここのnameがdue_dateになっていないのでsqlの due_dateと紐付かないです！

2020-02-29 02:24 UTC, Arisaarisa commented on index.php
> +      <input type="date" name="date" value="<?php echo h($due_date); ?>">
ここもnameがdue_dateじゃないので紐付かないです！

2020-02-29 02:24 UTC, Arisaarisa commented on index.php
> +      <?php if ($errors) : ?>
ここはカウント関数でまわしたいのでhintを参照してみて下さい！

https://23seiki.gitbook.io/php/php/exercises/01-3#hint

```
// if文条件定義の後、htmlに
<?php if (count($*****) > 0) : ?>
  <ul "ここはカリキュラムだと直接書き込んでいますがerror-list紐付くように">
    <?php foreach ($***** as $key => $value) : ?>
      <li><?php echo h($value); ?></li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
```

2020-02-29 02:24 UTC, Arisaarisa commented on edit.php
> +  <?php if ($errors) : ?>
ここもcount関数でやりましょう！

2020-03-04 14:10 UTC, Yuina-Kage commented
お疲れさまです！
課題つまづいてしまったのでご確認お願い致します。

<期待する動作>
①学習内容と期限を編集するとメインページにとび、編集後が表示される。
②dua_dateの昇順・降順でデータを表示。

<うまくいかない点 or エラーの内容>
①編集画面で編集ボタンを押すとメインページにとぶことができるが、何も変わらない。
②何も変わらない。

<自分なりに考えて試した点>
①edit.phpの33行目(エラーが1つもなければレコードを更新)の部分に問題があるのではないかと思い、due_dateとtitleで文を分けてみたが何も変わらない。
②ORDER BY句を使用し、昇順(asc)、降順(desc)を使うのではないかと思い、
index.htmlの77~、93~に入れるのではないかと思っているのですが想像がつかない状態。
それとも書くところ自体間違いでPHPの方なのかつまづいてしまっている状態。

よろしくお願い致します。

2020-03-05 10:59 UTC, Arisaarisa reviewed
昇降順は関係ないと思います！！
編集された内容が通らないのはedit.phpで編集の更新が通らないからと考えます！！
下記を修正して実装確認してみてください🌟

2020-03-05 10:59 UTC, Arisaarisa commented on index.php
> +$sql = "select * from plans where status = 'notyet'";
昇順に並べ替えて下さい！

2020-03-05 10:59 UTC, Arisaarisa commented on index.php
> +$sql2 = "select * from plans where status = 'done'";
こちらは降順にならべかえましょう！

2020-03-05 10:59 UTC, Arisaarisa commented on index.php
> +      <?php if (count($_POST) > 0) : ?>
ここは`count($_POST)`ではなくエラーの数をカウントするので`count($errors)`です！

2020-03-05 10:59 UTC, Arisaarisa commented on index.php
> +    <?php foreach ($notyet_plans as $plan) : ?>
ここは期限日が過ぎたものは赤文字で表示できるようにしてください！！
ヒントをみてください😊
https://23seiki.gitbook.io/php/php/exercises/01-3#hint

2020-03-05 10:59 UTC, Arisaarisa commented on edit.php
> +  if ($title == '') {
ここはもしタイトルが`空`の場合ではなく、`postされたタイトルと変更点がなかったら`になります

2020-03-05 10:59 UTC, Arisaarisa commented on edit.php
> +  if ($due_date == '') {
ここも`空`の場合ではなく、変更点がなかったらです！

2020-03-05 10:59 UTC, Arisaarisa commented on edit.php
> +    $sql = "update plans set title = :title, updated_at = now() where id = :id";
titleだけではなくdue_dateの更新もしないといけません。
同時にbindParamが必要になるのもわかりますか？！

2020-03-05 10:59 UTC, Arisaarisa commented on edit.php
> +    $sql = "update plans set due_date =:due_date updated_at = now() where id = :id";
ここはtitleと分ける必要はありません。

2020-03-05 10:59 UTC, Arisaarisa commented on edit.php
> +    <?php if (count($_POST) > 0) : ?>
countするのはエラーの数です！

2020-03-06 23:51 UTC, Yuina-Kage commented
お疲れさまです！
たくさんのヒントをいただいていたのですが1つ何度考えても分からなかった所があり、何か助言をいただきたいです。

<期待する動作>
・未達成の所を昇順、達成済みの所を降順に並べる。

<うまくいかない点 or エラーの内容>
・達成済みがはじめからでてしまっている。
が、完了を押すとテーブルプラスではdoneになっている。

<自分なりに考えて試した点>
・descとascを使用し昇順降順に並べようとしたがうまく反映されない。

今、select文が2個ずつになっているのですが1つにまとめるのでしょうか？
提出も遅れており申し訳ございません。
よろしくお願い致します。

2020-03-07 01:22 UTC, Arisaarisa reviewed
最初から達成済みのところに表示がでるとのことでしたが、前にどこかがエラーの状態で通ってなかったアクションがコードが正しくなったので一気に通っただけかもしれないです！
一度テーブルの中身のデータをテーブルプラスから削除してみてもう一回追加してみてはどうでしょう？

2020-03-07 01:22 UTC, Arisaarisa commented on index.php
> +$sql2 = "select * from plans where status = 'done'";
ここは1つにまとめて下さい！！

2020-03-07 01:22 UTC, Arisaarisa commented on index.php
> +$sql = "select * from plans order by updated_at desc";
ここも1つにまとめられるのでまとめましょう！！

2020-03-07 16:23 UTC, Yuina-Kage commented
夜分遅くにすみません。
課題終わったのでご確認お願い致します。

何とか完成することができましたが提出大幅に遅れてしまい申し訳ございません。
色々とアドバイスありがとうございます！

![image](https://user-images.githubusercontent.com/58411035/76146982-5944b200-60db-11ea-988d-4d17f411dde5.png)

2020-03-08 08:28 UTC, Arisaarisa commented
今のままだと編集のページで何も変更しなくても登録できてしまうので、
編集ページ(edit.php)の中で条件に合うようにエラーを表示してください！！
ちなみに前回も修正をコメントしてます！！
https://github.com/Yuina-Kage/05_learning_plan/pull/1#discussion_r388210201
https://github.com/Yuina-Kage/05_learning_plan/pull/1#discussion_r388210568
<img width="805" alt="課題_06_学習管理アプリ_-_php" src="https://user-images.githubusercontent.com/45112341/76159246-b8e5a080-6161-11ea-9960-ad275f52ae00.png">

2020-03-08 08:33 UTC, Arisaarisa commented
提出する際は必ずすべての動作に間違いがないか自分で確認してから提出するようにしてください😊
次に提出する際は動作確認のスクショを一枚ではなく動作確認ごと(エラーが正しいか、登録できてるか、更新ができているか)のある程度枚数スクショをお願いします！！(index.phpでの動作、edit.phpでの動作など)

2020-03-11 04:28 UTC, Yuina-Kage commented
お疲れさまです。
提出遅くなり申し訳ございません。
課題のご確認お願い致します！

![image](https://user-images.githubusercontent.com/58411035/76277770-fdda1600-62cc-11ea-9b04-4a4c31e71a6c.png)
![image](https://user-images.githubusercontent.com/58411035/76277772-05012400-62cd-11ea-969f-01f97bec2dcb.png)
![image](https://user-images.githubusercontent.com/58411035/76277780-09c5d800-62cd-11ea-9cae-19edaae40555.png)
![image](https://user-images.githubusercontent.com/58411035/76277785-0f232280-62cd-11ea-8892-df6484583108.png)
![image](https://user-images.githubusercontent.com/58411035/76277789-134f4000-62cd-11ea-9eec-d9f3cd234870.png)
![image](https://user-images.githubusercontent.com/58411035/76277794-177b5d80-62cd-11ea-8282-59ee1d63a1ad.png)
![image](https://user-images.githubusercontent.com/58411035/76277803-1ba77b00-62cd-11ea-9240-664755de50d0.png)
![image](https://user-images.githubusercontent.com/58411035/76382222-4fe96d00-639b-11ea-8636-e8a8be0a2395.png)
![image](https://user-images.githubusercontent.com/58411035/76277808-206c2f00-62cd-11ea-9ddf-5b77a8f18489.png)
![image](https://user-images.githubusercontent.com/58411035/76277812-2530e300-62cd-11ea-8cc2-38ecd5fcc82d.png)
![image](https://user-images.githubusercontent.com/58411035/76277819-2bbf5a80-62cd-11ea-827a-3c1a50c00386.png)
![image](https://user-images.githubusercontent.com/58411035/76382181-334d3500-639b-11ea-951e-f7f212f072b9.png)

2020-03-11 04:48 UTC, Arisaarisa commented
お疲れ様です！！OKです✨

![LGTM](https://cdn.lgtmoon.dev/images/77534)

2020-03-11 14:32 UTC, merged